version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: stream-gateway-api
    container_name: stream-api
    environment:
      - NODE_ENV=production
      - HLS_DIR=/data/hls
      # لو أردت تمرير User-Agent أو تعطيل TLS تحقق:
      - FFMPEG_USER_AGENT=Mozilla/5.0
      - FFMPEG_TLS_VERIFY=0
    volumes:
      - ./hls:/data/hls
    ports:
      - "3000:3000"
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: stream-nginx
    depends_on:
      - api
    ports:
      - "8090:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web:/usr/share/nginx/html:ro
      - ./hls:/hls
    restart: unless-stopped
