services:
  api:
    build: ./api
    environment:
      - HLS_DIR=/data/hls
      - PORT=3000
      - MAX_JOBS=12    # ← غيّرها كما تشاء
    volumes:
      - ./hls:/data/hls
    ports:
      - "3000:3000"
    restart: unless-stopped

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web:/usr/share/nginx/html:ro
      - ./hls:/hls:ro
    ports:
      - "8090:80"
    depends_on:
      - api
    restart: unless-stopped
